apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bifrost.fullname" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
    {{- with .Values.server.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- with .Values.server.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "bifrost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bifrost.selectorLabels" . | nindent 8 }}

        {{- with .Values.server.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bifrost.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}

      {{- with .Values.server.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          command:
            - /bifrost
            - run
            - --config
            - /etc/server/bifrost.yaml

            {{- if and .Values.server.service.enabled .Values.server.monitoring.serviceMonitor.enabled }}
            - --metrics-host
            - '0.0.0.0'
            - --metrics-port
            - '2112'
            {{- end }}

          {{- with .Values.server.extraArgs }}
          args:
            {{ toYaml . | nindent 10 }}
          {{- end }}

          {{- with .Values.server.env }}
          env:
            {{ toYaml . | nindent 10 }}
          {{- end }}

          {{- with .Values.server.envFrom }}
          envFrom:
            {{ toYaml . | nindent 10 }}
          {{- end }}

          # TODO: Good first issue
          {{- with .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}

          volumeMounts:
            - name: server-config
              mountPath: /etc/server/
            {{- with .Values.server.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

        {{- with .Values.server.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: server-config
          configMap:
            name: {{ include "bifrost.fullname" . }}-config
        {{- with .Values.server.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}


