{{- if and .Values.server.service.enabled .Values.server.monitoring.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bifrost.fullname" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
    {{- with .Values.server.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- with .Values.server.monitoring.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
    scheme: http
    targetPort: 2112

    honorLabels: true

    {{- if .Values.server.monitoring.serviceMonitor.interval }}
    interval: {{ .Values.server.monitoring.serviceMonitor.interval }}
    {{- end }}

    {{- if .Values.server.monitoring.serviceMonitor.metricRelabelings }}
    metricRelabelings:
    {{ tpl (toYaml .Values.server.monitoring.serviceMonitor.metricRelabelings | nindent 6) . }}
    {{- end }}

    {{- if .Values.server.monitoring.serviceMonitor.relabelings }}
    relabelings:
    {{ tpl (toYaml .Values.server.monitoring.serviceMonitor.relabelings | nindent 6) . }}
    {{- end }}

    {{- with .Values.server.monitoring.serviceMonitor.tlsConfig }}
    tlsConfig:
    {{- toYaml . | nindent 6 }}
    {{- end }}

  selector:
    matchLabels:
      {{- include "bifrost.selectorLabels" . | nindent 6 }}
{{- end }}